version: "3"
services:
  app:
    container_name: gin_gorm_docker_gqlgen_crud
    build: .
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: gin_gorm_docker_gqlgen_crud_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
